# Usa una imagen base oficial de Python
FROM python:3.10

# Establece el directorio de trabajo
WORKDIR ./

# Copia el archivo de requisitos y el archivo de código fuente al contenedor
COPY requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY ./

# Exponer el puerto por defecto de Django
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["gunicorn", "mi_proyecto.wsgi:application", "--bind", "0.0.0.0:8000"]



# FROM python:3.10

# # Instalar dependencias del sistema
# RUN apt-get update && \
#     apt-get install -y build-essential cmake

# # Establecer el directorio de trabajo
# WORKDIR /app

# # Copiar archivos de la aplicación
# COPY requirements.txt .

# # Instalar dependencias de Python
# RUN pip install --upgrade pip && \
#     pip install -r requirements.txt

# # Copiar el código fuente de la aplicación
# COPY . .

# # Comando para ejecutar la aplicación
# CMD ["python", "app.py"]
