FROM python:3.10

# Instalar dependencias del sistema
RUN apt-get update && \
    apt-get install -y build-essential cmake

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar archivos de la aplicación
COPY requirements.txt .

# Instalar dependencias de Python
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copiar el código fuente de la aplicación
COPY . .

# Comando para ejecutar la aplicación
CMD ["python", "app.py"]
